### PR TITLE
Fix error with parametric types

### PR DESCRIPTION
**Pull request by staticfloat**
Using @jamii's fix from #17, I can confirm that this seems to work for my workload.

### CODE REVIEW

**Comment by staticfloat** [comment]
I've added a test, but it's difficult to know if it works because the rest of the tests are interfering.  ;)

**Comment by staticfloat** [comment]
Even with this change, trying to step through methods that make heavy use of parametric types (such as batchnorm invocation) fails very often with things like:

```
julia> @enter BN_trk(x)
In BatchNorm(x) at /home/staticfloat/.julia/dev/Flux/src/layers/normalise.jl:114
114     size(x, ndims(x)-1) == length(BN.β) ||
115       error("BatchNorm expected $(length(BN.β)) channels, got $(size(x, ndims(x)-1))")
116     γ, β = BN.γ, BN.β

About to run: (ndims)(<suppressed 2594 bytes of output>)
1|debug > n
typeof(f) = typeof(getproperty)
getproperty
Tuple{BatchNorm{typeof(identity),TrackedArray{…,Array{Float32,1}},Array{Float32,1},Float64},QuoteNode}
ERROR: no unique matching method found for the specified argument types
Stacktrace:
 [1] error(::String) at ./error.jl:33
 [2] which(::Any, ::Any) at ./reflection.jl:1003
 [3] #determine_method_for_expr#23(::Bool, ::Function, ::Expr) at /home/staticfloat/.julia/dev/ASTInterpreter2/src/ASTInterpreter2.jl:285
 [4] #determine_method_for_expr at ./none:0 [inlined]
 [5] #enter_call_expr#25(::Bool, ::Function, ::Expr) at /home/staticfloat/.julia/dev/ASTInterpreter2/src/ASTInterpreter2.jl:376
 [6] enter_call_expr(::Expr) at /home/staticfloat/.julia/dev/ASTInterpreter2/src/ASTInterpreter2.jl:376
 [7] next_line!(::ASTInterpreter2.JuliaStackFrame, ::Array{ASTInterpreter2.JuliaStackFrame,1}) at /home/staticfloat/.julia/dev/ASTInterpreter2/src/interpret.jl:248
 [8] execute_command(::DebuggerFramework.DebuggerState, ::ASTInterpreter2.JuliaStackFrame, ::Val{:n}, ::SubString{String}) at /home/staticfloat/.julia/dev/ASTInterpreter2/src/commands.jl:50
 [9] (::getfield(DebuggerFramework, Symbol("##4#8")){REPL.Terminals.TTYTerminal,DebuggerFramework.DebuggerState,REPL.LineEdit.Prompt})(::REPL.LineEdit.MIState, ::Base.GenericIOBuffer{Array{UInt8,1}}, ::Bool) at /home/staticfloat/.julia/dev/DebuggerFramework/src/DebuggerFramework.jl:276
 [10] #invokelatest#1 at ./essentials.jl:754 [inlined]
 [11] invokelatest at ./essentials.jl:753 [inlined]
 [12] run_interface(::REPL.Terminals.TextTerminal, ::REPL.LineEdit.ModalInterface, ::REPL.LineEdit.MIState) at /home/staticfloat/tmp/julia-build/julia-master/usr/share/julia/stdlib/v1.2/REPL/src/LineEdit.jl:2273
 [13] run_interface at /home/staticfloat/tmp/julia-build/julia-master/usr/share/julia/stdlib/v1.2/REPL/src/LineEdit.jl:2267 [inlined]
 [14] RunDebugger(::Array{ASTInterpreter2.JuliaStackFrame,1}, ::REPL.LineEditREPL, ::REPL.Terminals.TTYTerminal) at /home/staticfloat/.julia/dev/DebuggerFramework/src/DebuggerFramework.jl:314
 [15] RunDebugger(::Array{ASTInterpreter2.JuliaStackFrame,1}) at /home/staticfloat/.julia/dev/DebuggerFramework/src/DebuggerFramework.jl:240
 [16] top-level scope at /home/staticfloat/.julia/dev/ASTInterpreter2/src/ASTInterpreter2.jl:479

```

**Comment by staticfloat** [comment]
Interestingly, using `s` to step through seems to work whereas `n` does not.

**Comment by Keno** [comment]
I'll assign @KristofferC, since he's taking charge of this.

**Comment by KristofferC** [comment]
@Keno, Travis is still not activated here, right?

**Comment by Keno** [comment]
I guess it broke when I moved the repo. Let me try setting it up again.

**Comment by Keno** [comment]
Alright should be fixed I think.

**Comment by KristofferC** [comment]
Should be obsolete.

**Pull request closed without merging**
